CREATE DATABASE SISTEMA_CLUB;
--DROP DATABASE SISTEMA_CLUB;
--USE master;
USE SISTEMA_CLUB
CREATE TABLE DEPORTE(
	ID_DEPORTE INT IDENTITY(1, 1) PRIMARY KEY,
	DESC_DEPORTE NVARCHAR(200) NOT NULL
);

CREATE TABLE REGLAMENTO(
	ID_REGLAMENTO INT IDENTITY(100, 1) PRIMARY KEY,
	NOMBRE_REGLAMENTO NVARCHAR(100) NOT NULL,
	DESC_REGLAMENTO NVARCHAR(500) NOT NULL,
	ESTADO NVARCHAR(50) NOT NULL,
	FECHA_CONFECCION DATETIME NOT NULL,
	FECHA_VIGENCIA DATETIME NOT NULL
);

CREATE TABLE CLUB(
	ID_CLUB INT IDENTITY(1, 1) PRIMARY KEY,
	DESC_CLUB NVARCHAR(200) NOT NULL,
	ID_REGLAMENTO INT
);

ALTER TABLE CLUB
ADD CONSTRAINT FK_REGLAMENTO
FOREIGN KEY (ID_REGLAMENTO)
REFERENCES REGLAMENTO(ID_REGLAMENTO) 
ON DELETE SET NULL

CREATE TABLE CLUB_DEPORTE(
	ID_CLUB INT,
	ID_DEPORTE INT,
	CONSTRAINT FK_CLUB_DEP PRIMARY KEY (ID_CLUB, ID_DEPORTE),
	CONSTRAINT FK_CLUB 
		FOREIGN KEY (ID_CLUB) REFERENCES CLUB(ID_CLUB),
	CONSTRAINT FK_DEPORTE
		FOREIGN KEY (ID_DEPORTE) REFERENCES DEPORTE(ID_DEPORTE)
);

INSERT INTO DEPORTE VALUES('NATACION'),('FUTBOL'),('VOLEY'),('HOCKEY'),('RUGBY')
INSERT INTO REGLAMENTO VALUES('REGLAMENTO 1', 'LOREM IMSUP ... LALALA', 'Vigente', '2016-08-02 12:00:00', '2016-08-02 10:00:00')
INSERT INTO CLUB VALUES('CLUB ATLETICO NEWELLS OLD BOYS', 100), ('CLUB ATLETICO ROSARIO CENTRAL', null), 
('CLUB ATLETICO CENTRAL CORDOBA', null)
INSERT INTO CLUB_DEPORTE VALUES(1, 2),(1, 5),(1, 3),(2, 2),(2, 1),(2, 5),(3, 1),(3, 2),(3, 4),(3, 5) 