//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace William_Santisteban_02_08_2016.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClubContext : DbContext
    {
        public ClubContext()
            : base("name=ClubContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLUB> CLUB { get; set; }
        public virtual DbSet<DEPORTE> DEPORTE { get; set; }
        public virtual DbSet<REGLAMENTO> REGLAMENTO { get; set; }
    }
}
