//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace William_Santisteban_02_08_2016.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPORTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPORTE()
        {
            this.CLUB = new HashSet<CLUB>();
        }
    
        public int ID_DEPORTE { get; set; }
        public string DESC_DEPORTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLUB> CLUB { get; set; }
    }
}
